# Site settings
title: OData .NET Libraries
email: odatafeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a central place that hosts information about the OData .NET libraries
  implemented by the OData team of Microsoft.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  odata

# Build settings
markdown: kramdown
